services:
   db:
      image: mongo:latest
      container_name: mongodb
      ports:
         - "27017:27017"
      environment:
         MONGO_INITDB_ROOT_USERNAME: user
         MONGO_INITDB_ROOT_PASSWORD: password
         MONGO_INITDB_DATABASE: db
         MONGO_INITDB_DATABASEHOST: db
      
   server:
      container_name: backend
      build:
         context: ./server
      env_file:
         -  ./server/.env
      depends_on:
         - db
      ports:  
         - "3000:3000"

   client:
      container_name: frontend
      build:
         context: ./client

      env_file:
         - ./client/.env
      depends_on:
         - server
      ports:  
         - "3001:3001"
