name: Docker Build & Deploy to EC2

on:
  push:
    branches:
      - main  # Runs when code is pushed to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build Docker Image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/docker-deploy-cicd

    - name: Push Docker Image to Docker Hub
      run: docker push ${{ secrets.DOCKER_USERNAME }}/docker-deploy-cicd

    - name: Deploy on EC2
      uses: appleboy/ssh-action@v0.1.4
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          # Navigate to your project folder
          cd /home/ubuntu/myapp
          docker pull ${{ secrets.DOCKER_USERNAME }}/docker-deploy-cicd
          docker stop myapp || true
          docker rm myapp || true
          docker run -d --name myapp -p 80:5000 ${{ secrets.DOCKER_USERNAME }}/docker-deploy-cicd
